### ISSUE TITLE
Disabling a single check for testifylint doesn't seem to work

### ISSUE THREAD

**Issue by jpeach** [golangci/golangci-lint#4187]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I tried to disable the `require-error` check in testifylint but is has no apparent effect. Running testifylint by hand seems to do the right thing:

```console
 /src/go/bin/testifylint -fix -enable-all -disable require-error ./...
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.55.1 built with go1.21.3 from 9b20d49d on 2023-10-25T10:03:43Z
```

</details>

### Configuration

<details>

```console
[linters]
  disable-all = true
  enable = [
    "bodyclose",
    "errcheck",
    "errname",
    "errorlint",
    "forcetypeassert",
    "gofumpt",
    "goimports",
    "gosec",
    "gosimple",
    "govet",
    "ineffassign",
    "staticcheck",
    "testifylint",
    "typecheck",
    "unconvert",
    "unused",
  ]

[linters-settings.testifylint]
  enable-all = true
  disable = [ "require-error" ]
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.21.1 linux/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/docker/.cache/go-build'
GOENV='/home/docker/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/src/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/src/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/Users/James-Peach/xxx/go.mod'
GOWORK='/Users/James-Peach/xxx/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build401779602=/tmp/go-build -gno-record-gcc-switches'```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
$ ./bin/golangci-lint run -v
INFO [config_reader] Config search paths: [...]
INFO [config_reader] Used config file .golangci.toml
INFO [lintersdb] Active 15 linters: [bodyclose errcheck errname errorlint forcetypeassert gofumpt goimports gosec gosimple govet ineffassign staticcheck testifylint unconvert unused]
INFO [loader] Using build tags: [sudo netnstest manual]
INFO [loader] Go packages loading at mode 575 (files|imports|name|types_sizes|compiled_files|deps|exports_file) took 13.270919564s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 299.940984ms
INFO [linters_context/goanalysis] analyzers took 11m13.016979127s with top 10 stages: buildir: 3m51.451820361s, goimports: 1m55.16626531s, buildssa: 1m22.959177054s, gofumpt: 28.323953006s, errorlint: 20.60919316s, unused: 19.22052943s, gosec: 13.797644294s, inspect: 10.832307581s, S1038: 10.014257942s, unconvert: 9.26964808s
INFO [runner] fixer took 0s with no stages
INFO [runner/skip_dirs] Skipped 18 issues from dir thirdparty/ziutek/rrd by pattern thirdparty
INFO [runner/skip_dirs] Skipped 13 issues from dir thirdparty/AkihiroSuda/go-netfilter-queue by pattern thirdparty
INFO [runner/max_same_issues] 755/758 issues with text "require-error: for error assertions use require" were hidden, use --max-same-issues
INFO [runner] Issues before processing: 2752, after processing: 3
INFO [runner] Processors filtering stat (out/in): skip_files: 2642/2642, diff: 758/758, fixer: 3/3, path_prettifier: 2642/2642, identifier_marker: 1244/1244, exclude: 1244/1244, nolint: 758/824, max_per_file_from_linter: 758/758, max_same_issues: 3/758, source_code: 3/3, cgo: 2642/2752, filename_unadjuster: 2642/2642, skip_dirs: 2611/2642, max_from_linter: 3/3, path_prefixer: 3/3, sort_results: 3/3, autogenerated_exclude: 1244/2611, exclude-rules: 824/1244, uniq_by_line: 758/758, path_shortener: 3/3, severity-rules: 3/3
INFO [runner] processing took 554.763841ms with stages: autogenerated_exclude: 212.618596ms, nolint: 189.910853ms, path_prettifier: 108.770911ms, exclude-rules: 23.553448ms, identifier_marker: 17.059241ms, skip_dirs: 1.627307ms, source_code: 453.525µs, cgo: 288.78µs, filename_unadjuster: 154.599µs, uniq_by_line: 132.721µs, max_same_issues: 100.798µs, fixer: 53.226µs, max_per_file_from_linter: 33.496µs, max_from_linter: 2.833µs, path_shortener: 1.305µs, skip_files: 657ns, diff: 401ns, sort_results: 381ns, exclude: 334ns, severity-rules: 277ns, path_prefixer: 152ns
INFO [runner] linters took 54.082249829s with stages: goanalysis_metalinter: 53.527352465s
xxx.go:31:2: require-error: for error assertions use require (testifylint)
	assert.NoError(t, err)
	^
xxx.go:47:2: require-error: for error assertions use require (testifylint)
	assert.NoError(t, err)
	^
xxx.go:88:2: require-error: for error assertions use require (testifylint)
	assert.NoError(t, err)
	^
INFO File cache stats: 1 entries of total size 6.1KiB
INFO Memory: 621 samples, avg is 1380.1MB, max is 2897.3MB
INFO Execution took 1m7.667248269s```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestHelloWorld(t *testing.T) {
	var err error
	assert.NoError(t, err)
}
```
```yaml
linters:
  disable-all: true
  enable:
    - testifylint

linters-settings:
  testifylint:
    enable-all: true
    disable:
      - require-error
```
```console
 golangci-lint run -v
INFO [config_reader] Config search paths: [./ /tmp/l /tmp / /Users/James-Peach]
INFO [config_reader] Used config file .golangci.yaml
INFO [lintersdb] Active 1 linters: [testifylint]
INFO [loader] Go packages loading at mode 575 (types_sizes|compiled_files|exports_file|imports|name|deps|files) took 980.842719ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 2.880137ms
INFO [linters_context/goanalysis] analyzers took 1.268084ms with top 10 stages: testifylint: 1.244245ms, typecheck: 23.839µs
INFO [runner] Processors filtering stat (out/in): path_prettifier: 1/1, skip_dirs: 1/1, exclude-rules: 1/1, sort_results: 1/1, exclude: 1/1, diff: 1/1, max_from_linter: 1/1, path_shortener: 1/1, severity-rules: 1/1, path_prefixer: 1/1, cgo: 1/1, filename_unadjuster: 1/1, skip_files: 1/1, autogenerated_exclude: 1/1, identifier_marker: 1/1, nolint: 1/1, uniq_by_line: 1/1, max_per_file_from_linter: 1/1, max_same_issues: 1/1, source_code: 1/1, fixer: 1/1
INFO [runner] processing took 1.2804ms with stages: nolint: 321.565µs, path_prettifier: 300.632µs, source_code: 257.817µs, autogenerated_exclude: 232.704µs, identifier_marker: 79.56µs, exclude-rules: 64.536µs, skip_dirs: 12.972µs, filename_unadjuster: 3.576µs, max_same_issues: 1.24µs, path_shortener: 1.092µs, uniq_by_line: 1.042µs, cgo: 750ns, max_from_linter: 601ns, max_per_file_from_linter: 419ns, skip_files: 385ns, fixer: 378ns, severity-rules: 324ns, exclude: 324ns, diff: 196ns, sort_results: 166ns, path_prefixer: 121ns
INFO [runner] linters took 228.752628ms with stages: goanalysis_metalinter: 227.322021ms
main_test.go:11:2: require-error: for error assertions use require (testifylint)
	assert.NoError(t, err)
	^
INFO File cache stats: 1 entries of total size 153B
INFO Memory: 14 samples, avg is 30.8MB, max is 49.6MB
INFO Execution took 1.227229246s
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by jpeach** [comment]
@Antonboom Does this look familiar?

**Comment by Antonboom** [comment]
@jpeach hi!

The latest version of `testifylint` is not released in `golangci-lint` yet.

**Comment by ldez** [comment]
> maybe we can make the new patch? Or are you waiting for more changes?

I merged new things, so no path release, you will fave to wait for the next minor release.

**Comment by jpeach** [comment]
@ldez Can we keep this open and close it when the PR to make the "disable" option work lands?

**Comment by momashell** [comment]
@ldez this feature still is not available!

**Comment by gabrix-dev** [comment]
I am still having this problem on golangci-lint version 1.59.1, trying to disable require-error. I have tried various combinations but non seem to work.

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/issues/4187#issuecomment-1798282092

**Comment by gabrix-dev** [comment]
> ```yaml
> linters-settings:
>   testifylint:
>     disable:
>       - require-error
> ```

I have already tried this, I have also tried the enable config mentioned in this issue.
