### ISSUE TITLE
go1.24 support

### ISSUE THREAD

**Issue by ldez** [golangci/golangci-lint#5225]
**EDIT: since v1.64 golangci-lint supports go1.24 if compiled with go1.24 :tada:**

#### Additional Notes

Some package systems (like **homebrew**, nix, etc.) are "slow" in propagating the new Go version.
After a new release of Go and golangci-lint, those systems can use an old Go version to compile golangci-lint resulting in a non-working binary (high memory usage, missing symbol, etc.).

In this situation, you should use the official binaries, or compile golangci-lint manually with the right Go version, or help these package systems to support this new Go version.

We are not responsible for package systems that don't use official binaries.

To validate the Go version used to compile: `golangci-lint version`

```console
$ golangci-lint version
golangci-lint has version 1.64.2 built with go1.24.0 from 1dae906b on 2025-02-11T21:44:55Z
```

---

#### Is golangci-lint support go1.24?

No, and yes.

Basically, golangci-lint supports Go versions that are lower or equal to the Go version used **to build it**.

In addition, of the Go version used to build it, some linters could need to be updated to support newer versions of Go, and internal pieces of golangci-lint could also need to be updated.

The current binaries from the releases page and the Docker images have been built with go1.23 and will be built with go1.23 as long as go1.24 is not GA.
So those binaries/images don't support go1.24 (new elements and internal Go changes).

https://golangci-lint.run/welcome/faq/#which-go-versions-are-supported

```mermaid
---
title: Is golangci-lint support go1.24?
---
flowchart
    A([compiled with go1.24?]) -- yes --> B([needs update of the internals of golangci-lint?])
    A -- no --> C((NO))
    B -- yes --> D([uses right internal pieces?])
    B -- no --> E((YES))
    D -- yes --> G((YES))
    D -- no --> F((NO))
```

You can follow the PR https://github.com/golangci/golangci-lint/pull/5224 to see the progress on this topic.

https://go.dev/wiki/Go-Release-Cycle

#### Additional Notes

Some package systems (like **homebrew**, nix, etc.) are "slow" in propagating the new Go version.
After a new release of Go and golangci-lint, those systems can use an old Go version to compile golangci-lint resulting in a non-working binary (high memory usage, missing symbol, etc.).

In this situation, you should use the official binaries, or compile golangci-lint manually with the right Go version, or help these package systems to support this new Go version.

We are not responsible for package systems that don't use official binaries.

To validate the Go version used to compile: `golangci-lint version`

```console
$ golangci-lint version
golangci-lint has version 1.64.2 built with go1.24.0 from 1dae906b on 2025-02-11T21:44:55Z
```

---

`golangci-lint` is a free and open-source project built by volunteers.

If you value it, please consider donating or asking your company to do so, we appreciate it! :heart:

[![Open Collective backers and sponsors](https://img.shields.io/badge/OpenCollective-Donate-blue?logo=opencollective&style=for-the-badge)](https://opencollective.com/golangci-lint) [![GitHub Sponsors](https://img.shields.io/badge/GitHub-Donate-blue?logo=github&style=for-the-badge)](https://github.com/sponsors/golangci)

---

- [x] https://github.com/Antonboom/nilnil/pull/47

**Comment by pdarulewski** [comment]
Go 1.24 will introduce the `tool` directive: https://tip.golang.org/doc/modules/managing-dependencies#tools so it won't be needed to create `tools.go` with build tags.

Does it change anything in terms of recommendations for installing `golangci-lint` from sources [here](https://golangci-lint.run/welcome/install/#install-from-sources)? I think it would be nice to have all tools (linters, formatters, code generations, etc.) in a single place, so everyone in a team could use the same toolset, regardless of the package manager and operating system.

**Comment by ldez** [comment]
> Does it change anything in terms of recommendations for installing golangci-lint from sources [here](https://golangci-lint.run/welcome/install/#install-from-sources)?

No, this doesn't change the core of the problem.

The arguments inside the doc are more than accurate with this new command because it will merge the dependencies of your projects with the dependencies of the tools.

**Comment by titpetric** [comment]
https://github.com/golang/go/issues/66518 seems impacting us to use golangci beyond >1.22.7 (current go.mod).

From my limited understanding a release needs a go.mod >=1.23.4 tagged to enable upgrading to 1.23 or beyond. As long as the bug is open, generally anyone not building from source but using `go install` may face issues. It also explains some issues with typecheck failing.

**Comment by ldez** [comment]
This is not related to go1.24.

> From my limited understanding a release needs a go.mod >=1.23.4 tagged to enable upgrading to 1.23 or beyond.

There is confusion between the toolchain version and the min Go version.

https://go.dev/doc/toolchain#version
https://go.dev/ref/mod#go-mod-file-go

The doc uses the terms "language version", "release family", "version syntax", "version", "release", and "released versions" to talk about the same topic, this creates confusion on where each element can be used.

The min Go version can be a language version (`1.23`) and also a "version" (`1.23.0`).

The toolchain version is a "version" only (`1.23.0`).

Currently, golangci-lint requires min go1.23.1, because it depends on staticcheck that defined go1.23.1 as the min version.

There is no need to use a patched version higher than go1.23.1.

---

Just a reminder, we discourage the usage of `go install`, tools patterns, or tool directives to install golangci-lint.

https://golangci-lint.run/welcome/install/#install-from-sources

**Comment by leonklingele** [comment]
fyi: Go 1.24 just landed.

**Comment by ldez** [comment]
I have a problem with the release, I'm on the topic.

https://github.com/golangci/golangci-lint/actions/runs/13271625662/job/37052177243#logs

**Comment by ldez** [comment]
There is a change inside the GitHub Action: mono is missing.

So I disabled Chocolatey.

I will try to find the reason for the disappearance of mono later.

**Comment by ldez** [comment]
I was forced to create bugfix releases because of the problem related to Chocolatey, so v1.64.0 and v1.64.1 has been cancelled, v1.64.2 is the stable release.

**Comment by ldez** [comment]
@pfi79 could open an issue on https://github.com/daixiang0/gci?

**Comment by ldez** [comment]
I open a PR on gci https://github.com/daixiang0/gci/pull/227

**Comment by srenatus** [comment]
> Bumping to the latest release, 1.64.2, for using golangci-lint with Go 1.24, I got a panic from revive: [mgechev/revive#1228](https://github.com/mgechev/revive/issues/1228) -- Sharing this here because others might be running into the same thing.

My problem was resolved by https://github.com/golangci/golangci-lint/pull/5399. Thanks for publishing a new release so quickly. 👏

**Comment by ldez** [comment]
I hope you enjoyed my work, please consider donating or asking your company to do so.
My only source of revenue is donations.
This will be appreciated, thank you :heart:

https://donate.golangci.org/ 
https://donate.ldez.dev/

**Comment by pfouilloux** [comment]
Sorry for the necro post but it's still pinned and people may come looking on how go tools can be used 😅 

> No, it doesn't change the core of the problem, it will just increase the problems.
> 
> The arguments inside the doc are even more than accurate with this new command because, for example, it will merge the dependencies of your projects with the dependencies of the tools.

This is absolutely valid ☝ But there is a way to keep dependencies isolated by using a separate modfile for each tool:

```console
go mod init -modfile=go.golangci-lint.mod golanci-lint.com
go get -tool -modfile=go.golangci-lint.mod github.com/golangci/golangci-lint/cmd/golangci-lint
```

You then get a separate sum file for just golangci-lint :) It doesn't fix the other issues with installing from source though...

```console
❯ ll | grep go.
-rw-r--r--@  1 pfx  staff   9.2K Mar 14 10:45 go.golangci-lint.mod
-rw-r--r--@  1 pfx  staff    95K Mar 14 10:45 go.golangci-lint.sum
-rw-r--r--@  1 pfx  staff   8.8K Mar 14 09:58 go.mod
-rw-r--r--@  1 pfx  staff    94K Mar 14 09:58 go.sum
```

**Comment by ldez** [comment]
Yes, I discovered that before my first answer, but the problems are still here:
- go version used to build
- dependencies can be updated by hand

I plan to document that in detail.

**Comment by mcandre** [comment]
Note that very many Go linters, including nakedret, nonamedreturns, and more, crash when scanning Go 1.24(.1) application code. This is usually because their x dependencies are behind. The golangci-lint high level utility may be Go 1.24.1 compatible, but the underlying linters are not.

**Comment by ldez** [comment]
This is wrong: v1.64 works with go1.24, and all the linters too.

The golangci-lint versions before v1.64 don't work with go1.24, even if compiled with go1.24, as explained in the schema from the issue description.

**Comment by mcandre** [comment]
nakedret has open bugs with Go 1.24.1, see their GitHub issues.
